Repository Vonage/vivid, pull requests merged in 2022-02, with the labels that each got.

#1230 fix(workspace): resolve missing dependencies
  .depcheckrc
  common/design-tokens/package.json
  components/banner/package.json
  components/button/package.json
  components/card/package.json
  components/elevation/package.json
  components/empty-state/package.json
  components/fab/package.json
  components/file-picker/package.json
  components/icon-button/package.json
  components/layout/package.json
  components/snackbar/package.json
  components/switch/package.json
  components/tags/package.json
  components/text/package.json
  components/textfield/package.json
Labels: Type: Bug :lady_beetle:, dependencies

#1214 feat(vwc-popup): change anchorEl to anchorId
  components/popup/src/vwc-popup-base.ts
  components/popup/stories/popup.stories.js
  components/popup/test/popup.test.js
  ui-tests/snapshots/vwc-popup.png
  ui-tests/tests/vwc-popup/index.js
Labels: Type: Component 🛠

#1192 fix(snackbar): support heading in non legacy mode
  __snapshots__/snackbar.md
  components/snackbar/src/vwc-snackbar.scss
  components/snackbar/src/vwc-snackbar.ts
  components/snackbar/stories/snackbar.js
  ui-tests/snapshots/vwc-snackbar.png
  ui-tests/tests/vwc-snackbar/index.js
Labels: Type: Feature, Type: Component 🛠
